ARG VERSION=1.3.7
FROM harbor.services.osism.tech/thecloudsphere/terraform/base:${VERSION}

ARG TERRAGRUNT_VERSION=0.43.0

ADD https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 /environment/terragrunt
COPY files/Makefile /environment/Makefile
RUN chmod +x /environment/terragrunt
