ARG VERSION=1.2.7
FROM harbor.services.osism.tech/timon/terraform/base:${VERSION}

COPY files/main.tf /environment/main.tf
COPY files/run.sh /environment/run.sh

RUN /environment/terraform init \
    && rm /environment/.terraform/terraform.tfstate
