ARG BASE_VERSION=latest
FROM harbor.services.osism.tech/thecloudsphere/base:${BASE_VERSION}

ENV VERSION=1.26.1

ADD https://dl.k8s.io/release/v${VERSION}/bin/linux/amd64/kubectl /environment/kubectl

COPY files/Makefile /environment/Makefile

RUN chmod +x /environment/kubectl
