ARG UBUNTU_VERSION=22.04
FROM ubuntu:${UBUNTU_VERSION}

ENV VERSION=1.24.3
ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ADD https://dl.k8s.io/release/v${VERSION}/bin/linux/amd64/kubectl /environment/kubectl

COPY files/Makefile /environment/Makefile
COPY files/run.sh /environment/run.sh

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        dumb-init \
        git \
        make \
        openssh-client \
        rsync \
    && chmod +x /environment/kubectl \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /blueprint /input /output /processing /export /cache

WORKDIR /environment

VOLUME /blueprint /input /output /processing /export /cache

ENTRYPOINT ["/usr/bin/dumb-init", "--"]

LABEL "org.opencontainers.image.documentation"="https://docs.timon.tech" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/timontech/registry" \
      "org.opencontainers.image.url"="https://www.osism.tech" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
