ARG VERSION=1.2.5
FROM harbor.services.osism.tech/timon/terraform/base:${VERSION}

ARG TERRAGRUNT_VERSION=0.38.12

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ADD https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 /environment/terragrunt
COPY files/Makefile /environment/Makefile
RUN chmod +x /environment/terragrunt
