ARG BASE_VERSION=latest
FROM harbor.services.osism.tech/thecloudsphere/base:${BASE_VERSION}

ENV VERSION=1.4.6

ADD https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip /environment/terraform.zip

COPY files/Makefile /environment/Makefile
COPY files/tcs-backend.hcl /environment/tcs-backend.hcl
COPY files/tcs-backend.tf /environment/tcs-backend.tf
COPY files/tcs.tfrc /environment/tcs.tfrc

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        unzip \
    && unzip -d /environment /environment/terraform.zip \
    && rm -f /environment/terraform.zip \
    && apt-get remove -y \
        unzip \
    && rm -rf /var/lib/apt/lists/*
